### ISSUE TITLE
Installation whitelabel

### ISSUE THREAD

**Issue by Homerost** [ProjectOpenSea/opensea-whitelabel#17]
Hi.
Are there specialists here who can install whitelabel on my domain? I don't understand anything about this))

Приветствую всех.
Ничего в этом не понимаю, есть здесь кто может установить whitelabel на мой домен?

**Comment by ayyoub512** [comment]
Hi, I can help you with that, I have just helped many clients do the same, my last two projects were all Whitelabel websites you can check here https://nftforyou.io/ http://nftformusic.io/

**Comment by Homerost** [comment]
> Hi, I can help you with that, I have just helped many clients do the same, my last two projects were all Whitelabel websites you can check here https://nftforyou.io/ http://nftformusic.io/

Thanks, but that's not really what I'm looking for. Your example is inserting an iFrame into a site page. I need https://github.com/ProjectOpenSea/opensea-whitelabel

**Comment by ayyoub512** [comment]
With the current issues on this repo, that's the best path I found.

**Comment by Homerost** [comment]
Very sorry...

**Comment by Homerost** [comment]
> With the current issues on this repo, that's the best path I found.

what are the current issues on this repo, did you mean?

**Comment by Homerost** [comment]
It is clear, there is a dead sea ...
