### ISSUE TITLE
Purchase buttons "Buy now" and "Make offer" on tokens page not working

### ISSUE THREAD

**Issue by netskycz** [ProjectOpenSea/opensea-whitelabel#31]
Hello,

The token purchase buttons do not work at this time when use iframe version.

Demo:
https://www.sneakrcred.com/crazyj

Open any token > click "Buy now"

This probably has to be solved on OpenSea.io, is it solvable?

Thanks for help

**Comment by hgrey517** [comment]
not working for me either. Did you get any update?

**Comment by netskycz** [comment]
> not working for me either. Did you get any update?

its fixed now
